### ISSUE TITLE
Connecting Tally to Power BI

### ISSUE THREAD

**Issue by sau6402** [dhananjay1405/excelkida-power-query-library#1]
Hi,

I tried the power query code in Microsoft Power BI. And it works.

But, I was thinking if there is any way to connect to entire Tally Data Model/Database.
So we have all Ledgers, Inventory, Bill i.e different tables  and then create a Data Model in Power BI.

It could help the community build reports based on Tally in Power BI.

Let me know if there is a possibility. 

--
Regards
Saurabha Joglekar

**Comment by dhananjay1405** [comment]
Hi,
Actually there is no direct way to connect to Tally Database like we connect to other sources (like CSV, SQL Server) in Power BI. There is no native connector by Tally for Power BI (like for Quickbooks, Salesforce). Tally database tables and fields have been documented in Tally Developer software (you need to install educational version from their official website). Tally XML Server exposes complete database, and you need to send XML to Tally via Power Query (from Excel or Power BI as per your choice). This XML needs to be drafted in TDL Language as documented in their External Integration documentation (which is vague and incomplete)

Using ODBC you can connect to few tables (voucher table only any single day) and also suffers restriction of 32/64 bit connectivity

I am working on developing project, which will offload its database structure and clone it in MS-SQL Server or MySQL. Will announce when that project is complete (exploration in progress)

**Comment by shashankshirke** [comment]
Hi guys,

This is exactly what I am looking for but found nothing useful so far.

We need a way to connect to the Tally database in its entirety so that it can then be mirrored onto another DBMS like MySQL which is much more easier to work with when it comes to 3rd party BI tools.

As I see there are 2 approaches to this:

1) Build a native connector to Tally-XYZ BI application.

2) Figure out a way to mirror Tally database onto a different DBMS. 

The first approach will be restrictive to that specific pair while the second approach will be much more universal and extensible.

@dhananjay1405 looking forward to learn more about the project you mentioned.

**Comment by sau6402** [comment]
Hi Dhanajay,

Thanks for your detailed reply. 

I did not find any good resources to check on the XML tally thing. 
Its quite tricky and not very straight forward.

Did you find time to get anything working on the database offloading thing. I think that is something I was looking for.
My logic was to help understand the DB structure and create multiple pq scripts. But, offloading is best.

Would love to contribute if you need some help with that.

--
Regards
Saurabha J

**Comment by dhananjay1405** [comment]
Hi All,
Since you all are too exploring things like me, let me reveal some XML related things, which will help you out in achieving what you all want. Please follow the steps as below

1. Open any of my Power Query script of Tally
2. In that locate a line body = "..." 
3. Copy-paste contents inside double quote in Notepad++
4. Replace 2 double quotes with single double quote (called unescaping string)
5. In Notepad++ (install XML plugin), & Plugins > XML Tools > Pretty Print
6. You will discover the real XML, which contains TDL & does the real magic of fetching data from Tally

@sau6402  you can develop equivalent of this in Python to send such XML using HTTP WebRequest with POST method (XML in body of Request) & in return you will get the result you want in Body of Response. Just ignore HTTP Content-Type header of text/xml in HTTP Response, & treat it as text/csv
(sorry I am NodeJS developer programming in Javascript, & do not know Python programming)

**Comment by dhananjay1405** [comment]
Hi Guys,
Since many people are interested in knowing what exact XML is exchanged with Tally to get results, so I have now made that folder public on this project named **Supporting_XML** which contains TDL formatted XML for each Power Query. I have kept file name of Power Query & underlying XML same for easy reference.

I will suggest everyone of you to have a look of those files, as that XML is pretty self-declarative. I am sure you all are versed with Python, C#, Java (or whichever language of your choice) & these XML files can easily be sent to Tally via HTTP Request using libraries of these languages. Or even PostMan or Telerik Fiddler (I am personally fan of Fiddler) like tools can be used to test output of these XML files.
Just dump the output you get from HTTP Request in Text files. Then use BULK INSERT (SQL Server) or LOAD DATA INFILE (MySQL) statements to import it into your respective database.

I hope this may serve as some starting point. I am very positive that some of you might cook-up a dedicated project for the customised loading into Database. Or let's see if I am able to cook some generic separate project in future.

Currently I will restrict this project only to Power Query (as it is the theme)

**Comment by dhananjay1405** [comment]
As of now I am closing this thread. Any open-source project on the above discussion would be floated on my GitHub account

**Comment by dhananjay1405** [comment]
I have re-opened this thread just to update @sau6402 and @shashankshirke both of you that Tally to Database Server off-loading project in now live on my Github (  ), as you all were interested in such a project. It supports bulk loading of data into SQL Server, MySQL Server or MariaDB any of these popular databases. It is developed in Javascript running on Node.JS

Further discussion on this project we can continue on that repository

**Comment by shashankshirke** [comment]
> I have re-opened this thread just to update @sau6402 and @shashankshirke both of you that Tally to Database Server off-loading project in now live on my Github ( ), as you all were interested in such a project. It supports bulk loading of data into SQL Server, MySQL Server or MariaDB any of these popular databases. It is developed in Javascript running on Node.JS
> 
> Further discussion on this project we can continue on that repository

Hi @dhananjay1405

Thanks for the update on this 👍

I'm going through the repo right now. I must say you've done a great job at documenting the process in a detailed step-by-step way. I'll try it out and get back to you on this.

**Comment by sau6402** [comment]
Hi @dhananjay1405,

Thanks for the update !!!
I tried the code from the new repo and encountered a few roadblocks.

I have added them under issues in that repo, could you please have a look at them.

--
Regards
Saurabha J

**Comment by dhananjay1405** [comment]
> Hi @dhananjay1405,
> 
> Thanks for the update !!!
> I tried the code from the new repo and encountered a few roadblocks.
> 
> I have added them under issues in that repo, could you please have a look at them.
> 
> --
> Regards
> Saurabha J

@sau6402 it feels good that you have started exploring the new project. I have provided resolution to your bug in new repo itself against your issue thread. You should encounter that issue even for Power Query based import, & that fix will solve your problem for both Power Query & Database loading. Please check resolution

**Comment by EasyReportsMarketing** [comment]
Hi, one approach is to use a Tally connector to extract Tally data into SQL Server and then connect Power BI to the SQL database to build reports & Dashboards. Let's discuss.

**Comment by dhananjay1405** [comment]
@EasyReportsMarketing I already host an open-source project for this, where Tally data can be transferred to SQL Server / PostgreSQL / MySQL / Google BigQuery.
https://github.com/dhananjay1405/tally-database-loader
